#!/bin/zsh

if [ "$1" = "all" ]; then
    for setup_script in $DOTFILES/*/setup.sh; do zsh $setup_script; done
elif [ ! -z "$1" ]; then
    [ -f $DOTFILES/$1/setup.sh ] && zsh $DOTFILES/$1/setup.sh
fi
[[ "$1" = "zsh" || "$1" = "all" ]] && source $HOME/.zshrc
[[ "$1" = "tmux" || "$1" = "all" ]] && (tmux ls &>/dev/null && tmux source-file $HOME/.tmux.conf)
[ "$2" = "restart" ] && restart

